# 15.Área de un triángulo: Calcula el área de un triángulo dada su base y altura con 
# la fórmula (base * altura) / 2. Este ejercicio no requiere un ciclo for.

# se solicitara al usuario ingresa dos valores 
print("Vamos a calcular el área de un triangulo donde B es la base y H la altura utilizando la formula [BXH /2] ")
print("Por favor ingrese la base del triangulo B:")
B = int(input())
print("Por favor ingrese la altura del triangulo  H:")
H = int(input())
at=B*H/2  #area del triangilo 
print(f"El area del trinagulo es {at}:") 


